### ISSUE TITLE
Not showing up on Homeassistant Cast

### ISSUE THREAD

**Issue by rgogada** [kalkih/simple-weather-card#16]
Error: Custom element doesn't exist: simple-weather-card

Please let me know if you need a screenshot or something. CHeers.

**Comment by kalkih** [comment]
Hey!
Should be fixed with this https://github.com/kalkih/simple-weather-card/pull/14.
Will be available in a new release later today, thanks!

**Comment by rgogada** [comment]
> Hey!
> Should be fixed with this #14.
> Will be available in a new release later today, thanks!

awesome. thanks.

**Comment by kalkih** [comment]
New release is now available, let me know if it's fixed, thanks!

**Comment by rgogada** [comment]
I have updated the card and I am still seeing the error. I dont know if I need to clear cache or something. I dont know how to clear cache with homeassistant cast.

**Comment by rgogada** [comment]
I restarted everything and all good. thanks for fixing this.

**Comment by KTibow** [comment]
Not working for me with `cast.show_lovelace_view`, any troubleshooting ideas?

**Comment by Devqon** [comment]
Also not working for me currently. On HA 2021.4.4 and simple weather card v0.8.1. I don't get the error any more on my Google Home Hub, but the card isn't displaying at all.
